todo_manager/todo_list/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "todo_list"

urlpatterns = [
    # path("", views.index_view, name="index"),
    # path("", views.ToDoListIndexView.as_view(), name="index")
    path("", views.ToDoListIndexView.as_view(), name="index"),
    path("<int:pk>/", views.ToDoDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.ToDoItemUpdateView.as_view(), name="update"),
    path("<int:pk>/confirm-delete/", views.ToDoItemDeleteView.as_view(), name="delete"),
    path("list/", views.ToDoListView.as_view(), name="list"),
    path("done/", views.ToDoListDoneView.as_view(), name="done"),
    path("create/", views.ToDoItemCreateView.as_view(), name="create"),
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path('todos/', include('todo_list.urls')),
    path('admin/', admin.site.urls),
]

todo_manager/todo_list/models.py
from tabnanny import verbose
from django.db import models
from django.urls import reverse
from django.utils import archive

class ToDoItem(models.Model):
    class Meta:
        ordering = ("id", )
        verbose_name = "ToDo Item"

    title=models.CharField(max_length=(250))
    description = models.TextField(blank=True, null=False)
    done=models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

    def get_absolute_url(self):
         return reverse(
             "todo_list:detail",
             kwargs={"pk": self.pk},
         )

    def __str__(self):
        return self.title

todo_manager/todo_list/forms.py
from dataclasses import fields
from django import forms

from .models import ToDoItem

class ToDoItemCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ("title", "description")
        
        widgets = {
            "description" : forms.Textarea(attrs={"cols": 30, "rows": 5}),
        }

class ToDoItemUpdateForm(forms.ModelForm):
    class Meta(ToDoItemCreateForm.Meta):
        fields = ("title", "description","done")

todo_manager/todo_list/views.py
from msilib.schema import ListView
from pipes import Template
from typing import Any
from django.contrib.messages import success
from django.db.models import Model
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView, TemplateView, ListView, DetailView, CreateView, UpdateView

from .forms import ToDoItemCreateForm, ToDoItemUpdateForm
from .models import ToDoItem



def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = ToDoItem.objects.all()[:3]
    return render(
        request, 
        template_name="todo_list/index.html",
        context={"todo_items": todo_items},
    )

class ToDoListIndexView(ListView):
    template_name = "todo_list/index.html"
    # queryset = ToDoItem.objects.order_by('-id').all()[:2]
    queryset = ToDoItem.objects.all()[:2]

    
class ToDoListView(ListView):
    # model = ToDoItem
    queryset = ToDoItem.objects.filter(archived=False)
    

class ToDoListDoneView(ListView):
    queryset = ToDoItem.objects.filter(done=True).all()

class ToDoDetailView(DetailView):
    # model = ToDoItem 

    queryset = ToDoItem.objects.filter(archived=False)

class ToDoItemCreateView(CreateView):
    model = ToDoItem
    form_class = ToDoItemCreateForm
    # fields = ("title", "description")

    def get_success_url(self):
         return reverse(
             "todo_list:detail",
             kwargs={"pk": self.object.pk}, # type: ignore
         )
    
class ToDoItemUpdateView(UpdateView):
    model = ToDoItem
    template_name_suffix = "_update_form"
    form_class = ToDoItemUpdateForm
    

class ToDoItemDeleteView(DeleteView):
    model = ToDoItem

    success_url = reverse_lazy("todo_list:list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True # type: ignore
        self.object.save() # type: ignore
        return HttpResponseRedirect(success_url)

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Base Title
        {% endblock title %}
    </title>
</head>
<body>
    {% include "components/navbar.html" %}
    {% block body %}
        Base body!
    {% endblock body %}
    <footer>
        &copy; Django TODO App    
        {% block footer %}
        
        {% endblock  %}
    </footer>

    
</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
    <ul>
        <li><a href={% url "index" %}>Home</a></li>
        <li><a href={% url "todo_list:index" %}>ToDo List</a></li>
        <li><a href="#">About</a></li>
    </ul>
    
</nav>

todo_manager/templates/index.html
{% extends "base.html" %}

{% block title %}
    TODO App Index
{% endblock title %}

{% block body %}
    <h1>Wellcome to our TODO App!</H1>
    <h2>Work in progress</h2>
    <h3>{% now "jS F Y" %}</h3>
    
{% endblock body %} 

todo_manager/todo_list/templates/todo_list/base.html
{% extends "base.html" %}

{% block footer %}
    ToDo list
{% endblock  %} 

todo_manager/todo_list/templates/todo_list/components/todo_items_list.html
<ul>
    {% for todo_item in object_list %}
    <li>
        <a href="{% url "todo_list:detail" pk=todo_item.pk %}">
            {{ todo_item.title }}
            {% if todo_item.done%}
                ✅
            {% else %}
                ❌
            {% endif %}
        </a>
    </li>
    {% endfor %}
</ul>

todo_manager/todo_list/templates/todo_list/index.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo List App
{% endblock  %}

{% block body %}
    <h1>ToDo List App</h1>
    <ul>
        <li><a href="{% url "todo_list:list" %}"> All todo_items</a></li>
        <li><a href="{% url "todo_list:done" %}"> Done todo_items</a></li>
        <li><a href="{% url "todo_list:create" %}"> Create ToDo_Item</a></li>

    </ul>
    </div>
    <h2>ToDos:</h2>
    {% include "todo_list/components/todo_items_list.html" %}
{% endblock  %}

todo_manager/todo_list/templates/todo_list/todoitem_confirm_delete.html
{% extends "todo_list/base.html" %}

{% block title %}
    Confirm Delete ToDo Item #{{ object.pk }}
{% endblock  %}

{% block body %}
<h2>Confirm delete "{{ object.title }}"</h2>
<p>
    Are you sure want to delete ToDo Item {{ object.title }}
    with description <i>{{ object.description }}</i>
</p>
<form method="post">
    {% csrf_token %}
    {{ form }}
    ,<button type="submit">Delete</button>
</form>

<div>
    <a href="{% url "todo_list:detail" object.pk %}"
    >Back to ToDo Item details</a>
</div>

{% endblock  %}

todo_manager/todo_list/templates/todo_list/todoitem_detail.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo #{{ object.pk }}
{% endblock  %}

{% block body %}
    <h3>ToDo:</h3>
    <div>
        <div>Title:<strong>{{ object.title }}</strong></div>
        <div>Done:<strong>{{ object.done }}</strong></div>
        <div>Description:<strong>{{ object.description }}</strong></div>
    </div>

    <ul>
        <li>
            <a href="{% url "todo_list:update" object.pk %}"
            >Update ToDo Item</a>

        </li>
        <li>
            <a href="{% url "todo_list:delete" object.pk %}"
            >Delete ToDo Item</a>

        </li>
    </ul>

    </div>
    {% include "todo_list/components/todo_items_list.html" %}
{% endblock  %}

todo_manager/todo_list/templates/todo_list/todoitem_form.html
{% extends "todo_list/base.html" %}

{% block title %}
    Create new ToDo Item
{% endblock  %}

{% block body %}
    <h3>Create new ToDo:</h3>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
{% endblock  %}

todo_manager/todo_list/templates/todo_list/todoitem_list.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo List
{% endblock  %}

{% block body %}
    <h3>ToDos:</h3>
    {% include "todo_list/components/todo_items_list.html" %}
{% endblock  %}

todo_manager/todo_list/templates/todo_list/todoitem_update_form.html
{% extends "todo_list/base.html" %}

{% block title %}
    Update ToDo #{{ object.id }}
{% endblock  %}

{% block body %}
    <h3>Update ToDo:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

    <div>
        <a href="{% url "todo_list:detail" object.pk %}"
        >Back to ToDo Item details</a>
    </div>
{% endblock  %}